### ISSUE TITLE
automatically execute JS from non-editable code blocks

### ISSUE THREAD

**Issue by davelandry** [Datawheel/codelife#210]

**Comment by jhmullen** [comment]
note to self on this - will probably want to do this from within CodeEditor, as that's the place we know when our iframe is done loading and we can interact with it.  Consider a "executeOnLoad" switch that codeeditor can receive

**Comment by davelandry** [comment]
I would argue that all CodeEditors should "executeOnLoad", regardless of editable status. We would then just hide the "Execute" button on non-editable code blocks (or should we?).

**Comment by jhmullen** [comment]
I've added this in, but we need to consider its effects on Blizzard Island and the way we introduce `alert()`.  The execute button was originally added so that the alert doesn't pop up immediately before you've read the slide.

I do think we should keep the button there even for read-only slides, because if it _is_ something like alert, then you get to try it again and see.  But we still need a content-level solution for how we do alert in this situation.

**Comment by alexandersimoes** [comment]
I'm thinking an elegant solution might be to put a timeout of maybe 1/2 second… just so the next slide action completes before it executes
