### ISSUE TITLE
Facebook pixel install

### ISSUE THREAD

**Issue by f-carneiro** [Datawheel/codelife#408]
Copy the base code below and paste between the header tags on each page of your site:

<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window,document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
 fbq('init', '1441603452610632'); 
fbq('track', 'PageView');
</script>
<noscript>
 <img height="1" width="1" 
src="https://www.facebook.com/tr?id=1441603452610632&ev=PageView
&noscript=1"/>
</noscript>

**Comment by jhmullen** [comment]
This has been hardcoded into the server.jsx file on `master` so that codelife.com will have the script.

For future releases, the `develop` branch is waiting with a canon update that will set this via the environment variable `CANON_FACEBOOK_PIXEL` which has already been set in `codelife.service`

Currently waiting for @f-carneiro to check on the FB Pixel dashboard and confirm the setup is correct.

**Comment by jhmullen** [comment]
Closing this issue, as Fernanda confirmed it's working in `master`.
