### ISSUE TITLE
SelectGeo / SelectSchool — empty/unspecified option

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/codelife#409]
- All State, City, and School fields should have unspecified options. 
- The unspecified option should be the default option.
- The unspecified option should be selectable.

NOTE: This is a client request
ALSO NOTE: This will improve both the `contest signup form` (see tasks 1-3, issue #404) and the `edit profile view`

**Comment by jhmullen** [comment]
Due to the way all these callbacks and Brazilian State lookups/callbacks work, as strange as this sounds, unspecified options will require a bit more of a rewrite than expected.  As a stopgap, I have added a full checkbox opt-out for location (as we had for schools) and am moving this to "nice to have" for the moment.
